// <auto-generated />
using System;
using Coding_Test.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Coding_Test.Migrations
{
    [DbContext(typeof(CodingTestContext))]
    [Migration("20210426145551_intialMigration")]
    partial class intialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Coding_Test.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2021, 4, 26, 15, 55, 48, 439, DateTimeKind.Local).AddTicks(8644),
                            Email = "user1@domain.com",
                            Name = "User 1",
                            Password = "yOUX+/+CqjgLuHYGZrolWyaIBFQ7lLSAZfK7Fpktrdc=",
                            UpdatedAt = new DateTime(2021, 4, 26, 15, 55, 48, 442, DateTimeKind.Local).AddTicks(1887)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2021, 4, 26, 15, 55, 48, 493, DateTimeKind.Local).AddTicks(7653),
                            Email = "user2@domain.com",
                            Name = "User 2",
                            Password = "ldLO1Zoa1xlT8VGhdNIjXwCxn9Ff2A1WO0eQ/KiNDmg=",
                            UpdatedAt = new DateTime(2021, 4, 26, 15, 55, 48, 493, DateTimeKind.Local).AddTicks(7751)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2021, 4, 26, 15, 55, 48, 530, DateTimeKind.Local).AddTicks(8502),
                            Email = "user3@domain.com",
                            Name = "User 3",
                            Password = "sQel1UcHimuBXpoIRxeQP8pb7CBbddJEybbofCqaccQ=",
                            UpdatedAt = new DateTime(2021, 4, 26, 15, 55, 48, 530, DateTimeKind.Local).AddTicks(8565)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2021, 4, 26, 15, 55, 48, 563, DateTimeKind.Local).AddTicks(2810),
                            Email = "user4@domain.com",
                            Name = "User 4",
                            Password = "cbtylFp8cf7v6ehzmPKQSrV7gWakB8lKBx6QIqhlfnA=",
                            UpdatedAt = new DateTime(2021, 4, 26, 15, 55, 48, 563, DateTimeKind.Local).AddTicks(2874)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2021, 4, 26, 15, 55, 48, 597, DateTimeKind.Local).AddTicks(1106),
                            Email = "user5@domain.com",
                            Name = "User 5",
                            Password = "QI6wXgRvNrZO/Wiz5WZA25kha9BDjY3lMi4mS1q83/M=",
                            UpdatedAt = new DateTime(2021, 4, 26, 15, 55, 48, 597, DateTimeKind.Local).AddTicks(1178)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2021, 4, 26, 15, 55, 48, 631, DateTimeKind.Local).AddTicks(4634),
                            Email = "user6@domain.com",
                            Name = "User 6",
                            Password = "Tor+uPdA34FwwNQtpy3NrbNKYQ1OR+Lhwi4tXVNn6Qs=",
                            UpdatedAt = new DateTime(2021, 4, 26, 15, 55, 48, 631, DateTimeKind.Local).AddTicks(4695)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
