// <auto-generated />
using System;
using Coding_Test.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Coding_Test.Migrations
{
    [DbContext(typeof(CodingTestContext))]
    [Migration("20210427083820_addRefrestTokenToUsersTable")]
    partial class addRefrestTokenToUsersTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Coding_Test.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2021, 4, 27, 9, 38, 19, 479, DateTimeKind.Local).AddTicks(8013),
                            Email = "user1@domain.com",
                            Name = "User 1",
                            Password = "yOUX+/+CqjgLuHYGZrolWyaIBFQ7lLSAZfK7Fpktrdc=",
                            UpdatedAt = new DateTime(2021, 4, 27, 9, 38, 19, 480, DateTimeKind.Local).AddTicks(9516)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2021, 4, 27, 9, 38, 19, 500, DateTimeKind.Local).AddTicks(5959),
                            Email = "user2@domain.com",
                            Name = "User 2",
                            Password = "ldLO1Zoa1xlT8VGhdNIjXwCxn9Ff2A1WO0eQ/KiNDmg=",
                            UpdatedAt = new DateTime(2021, 4, 27, 9, 38, 19, 500, DateTimeKind.Local).AddTicks(6022)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2021, 4, 27, 9, 38, 19, 512, DateTimeKind.Local).AddTicks(3708),
                            Email = "user3@domain.com",
                            Name = "User 3",
                            Password = "sQel1UcHimuBXpoIRxeQP8pb7CBbddJEybbofCqaccQ=",
                            UpdatedAt = new DateTime(2021, 4, 27, 9, 38, 19, 512, DateTimeKind.Local).AddTicks(3746)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2021, 4, 27, 9, 38, 19, 522, DateTimeKind.Local).AddTicks(4025),
                            Email = "user4@domain.com",
                            Name = "User 4",
                            Password = "cbtylFp8cf7v6ehzmPKQSrV7gWakB8lKBx6QIqhlfnA=",
                            UpdatedAt = new DateTime(2021, 4, 27, 9, 38, 19, 522, DateTimeKind.Local).AddTicks(4043)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2021, 4, 27, 9, 38, 19, 532, DateTimeKind.Local).AddTicks(4556),
                            Email = "user5@domain.com",
                            Name = "User 5",
                            Password = "QI6wXgRvNrZO/Wiz5WZA25kha9BDjY3lMi4mS1q83/M=",
                            UpdatedAt = new DateTime(2021, 4, 27, 9, 38, 19, 532, DateTimeKind.Local).AddTicks(4585)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2021, 4, 27, 9, 38, 19, 543, DateTimeKind.Local).AddTicks(9215),
                            Email = "user6@domain.com",
                            Name = "User 6",
                            Password = "Tor+uPdA34FwwNQtpy3NrbNKYQ1OR+Lhwi4tXVNn6Qs=",
                            UpdatedAt = new DateTime(2021, 4, 27, 9, 38, 19, 543, DateTimeKind.Local).AddTicks(9261)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
